[build]
    command = "npm run build"
    publish = "dist/"

[dev]
    command = "npm run dev"
    autoLaunch = true
    framework = "#custom"
    targetPort = 3000

[[edge_functions]]
    path = "/fn/random"
    function = "random-article"