backend:
  name: git-gateway
  branch: master
media_folder: "public/img/"
local_backend: true
public_folder: "/dist/"
collections:
  - name: "article"
    label: "Article"
    folder: "src/content/articles"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Date"
        name: "pubDate"
        widget: "datetime"
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Verse"
        name: "verse"
        widget: "string"
        required: false
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Series"
        name: "series"
        widget: "string"
        required: false
      - label: "Flags"
        name: "flags"
        widget: "select"
        options: ["DRAFT", "RSS-ONLY"]
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Head"
        name: "head"
        widget: "code"
        required: false
        modes: ["html"]
        output_code_only: true
