backend:
  name: git-gateway
  branch: master
media_folder: "src/img/"
local_backend: true
public_folder: "/img/"
collections:
  - name: "note"
    label: "Note"
    folder: "src/notes"
    create: true
    identifier_field: number
    slug: "{{fields.number}}"
    fields:
      - label: "Number"
        name: "number"
        widget: "number"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Edited"
        name: "edited"
        widget: "boolean"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
